# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/" # Location of package manifests
    assignees:
      - "LunaPurpleSunshine"
    schedule:
      interval: "weekly"
      day: "sunday"
    # Python dev dependencies are separate so that they can have a different label
    # This is then used by release-drafter
    groups:
      development-dependencies:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
        exclude-patterns:
          - "ruff"
          - "mypy"
          - "pytest"

  - package-ecosystem: "github-actions"
    directory: "/"
    assignees:
      - "LunaPurpleSunshine"
    schedule:
      # Check for updates to GitHub Actions every week
      interval: "weekly"
      day: "sunday"
    # Group all github action together
    groups:
      github-actions:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
