# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/" # Location of package manifests
    allow:
      - dependency-type: production
    labels:
      - "dependencies:production"
      - "python"
    schedule:
      interval: "weekly"
      day: "sunday"

  # Python dev dependencies are separate so that they can have a different label
  # This is then used by release-drafter
  - package-ecosystem: "pip"
    directory: "/"
    allow:
      - dependency-type: development
    labels:
      - "dependencies:development"
      - "python"
    schedule:
      interval: "weekly"
      day: "sunday"
    groups:
      development-dependencies:
        dependency-type: "development"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every week
      interval: "weekly"
      day: "sunday"
