name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

categories:
  - title: 'Features'
    labels:
      - 'enhancement'
  - title: 'Bug Fixes'
    labels:
      - 'bugfix'
      - 'bug'
  - title: 'Documentation'
    labels:
      - 'documentation'
  - title: 'Updated Dependencies'
    labels:
      - 'dependencies:production'
  - title: 'Maintenance'
    labels:
      - 'maintenance'
      - 'dependencies:development'

change-template: '- $TITLE (#$NUMBER) by @$AUTHOR'  # @$AUTHOR not used here, names in Contributors section
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.

version-resolver:
  major:
    labels:
      - 'semver:major'
  minor:
    labels:
      - 'semver:minor'
  patch:
    labels:
      - 'semver:patch'
  default: patch

autolabeler:
  - label: 'maintenance'
    branch:
      - '/chore-.+/'
  - label: 'documentation'
    branch:
      - '/docs-.+/'
  - label: 'bug'
    branch:
      - '/fix-.+/'
      - '/bugfix-.+/'
  - label: 'enhancement'
    branch:
      - '/feature-.+/'
      - '/feat-.+/'

template: |
  # Changes

  $CHANGES
