version: '3.8'
services:
  devcontainer:
    image: "mcr.microsoft.com/devcontainers/python:1-3.11-bookworm"

    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    environment:
      # SQLite Test File Location
      IPGET_TEST_SQLITE_DATABASE: ":memory:"
      # MySQL Test Server
      IPGET_TEST_MYSQL_USERNAME: ipget-mariadb
      IPGET_TEST_MYSQL_PASSWORD: test-super-secure-password1
      IPGET_TEST_MYSQL_HOST: localhost
      IPGET_TEST_MYSQL_PORT: 3306
      IPGET_TEST_MYSQL_DATABASE: mariadb_test_db
      # PostgreSQL Test Server
      IPGET_TEST_POSTGRES_USERNAME: ipget-postgres
      IPGET_TEST_POSTGRES_PASSWORD: test-super-secure-password2
      IPGET_TEST_POSTGRES_HOST: localhost
      IPGET_TEST_POSTGRES_PORT: 5432
      IPGET_TEST_POSTGRES_DATABASE: postgres_test_db
  
  mysql:
    image: mariadb:11
    restart: unless-stopped
    network_mode: service:devcontainer
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: "yes"
      MARIADB_DATABASE: mariadb_test_db
      MARIADB_USER: ipget-mariadb
      MARIADB_PASSWORD: test-super-secure-password1

  postgres:
    image: postgres:15
    restart: unless-stopped
    network_mode: service:devcontainer
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres_test_db
      POSTGRES_USER: ipget-postgres
      POSTGRES_PASSWORD: test-super-secure-password2

volumes:
  mariadb-data:
  postgres-data: