version: '3.3'
services:
    # SQLite setup
    ipget_sqlite:
        image: ghcr.io/lunapurplesunshine/ipget
        environment:
            IPGET_DB_TYPE: SQLite # Required: Choose database type e.g. SQLite
        volumes:
            - /mnt/appdata/ipget/logs:/app/logs # Optional: Map log files
            - /mnt/appdata/ipget/public_ip.db:/app/public_ip.db # Required: Map database file, or it will not persist
    # MySQL/MariaDB setup
    ipget_mysql:
        image: ghcr.io/lunapurplesunshine/ipget
        environment:
            IPGET_DB_TYPE: MySQL # Required: Choose database type - MySQL requires futher configuration
            IPGET_LOG_LEVEL: WARNING
            IPGET_MYSQL_USERNAME: ipget_user
            IPGET_MYSQL_PASSWORD: password1
            IPGET_MYSQL_HOST: mariadb.example.com
            IPGET_MYSQL_PORT: 3306
            IPGET_MYSQL_DATABASE: ipget_db
        volumes:
            - /mnt/appdata/ipget/logs:/app/logs # Optional: Map log files
