name: Pull Request Validation
on:
  pull_request:
    types:
     - opened
     - reopened
     - edited
     - synchronize

jobs:
  check-not-wip:
    runs-on: ubuntu-latest
    steps:
      - name: WIP
        uses: wip/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
