name: Pull Request Validation
on:
  pull_request:
    types:
     - opened
     - reopened
     - edited

jobs:
  check-not-wip:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/GitHubSecurityLab/actions-permissions/tree/main/monitor
      - uses: GitHubSecurityLab/actions-permissions/monitor@v1
        with:
          config: ${{ vars.PERMISSIONS_CONFIG }}
      - name: WIP
        uses: wip/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
