name: Pull Request Validation
on:
  pull_request:
    types:
     - opened
     - reopened
     - edited

jobs:
  check-not-wip:
    runs-on: ubuntu-latest
    permissions:
      statuses: write
    steps:
      - name: WIP
        uses: wip/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  check-semver-label:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/GitHubSecurityLab/actions-permissions/tree/main/monitor
      - uses: GitHubSecurityLab/actions-permissions/monitor@v1
        with:
          config: ${{ vars.PERMISSIONS_CONFIG }}

      - id: prefix_label_check
        uses: agilepathway/label-checker@v1.5.9
        if: ${{!contains(github.event.pull_request.labels.*.name, 'documentation') && !contains(github.event.pull_request.labels.*.name, 'maintenance')}}
        with:
          prefix_mode: true
          one_of: "semver:"
          repo_token: ${{ secrets.GITHUB_TOKEN }}
