name: Pull Request Validation
on:
  pull_request:
    types:
     - opened
     - reopened
     - labeled
     - unlabeled
     - edited
     - synchronize

permissions: {}

jobs:
  check-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Check semver label
        id: semver_label_check
        uses: agilepathway/label-checker@v1.6.32
        if: ${{!contains(github.event.pull_request.labels.*.name, 'documentation') && !contains(github.event.pull_request.labels.*.name, 'maintenance')}}
        with:
          prefix_mode: true
          one_of: "semver:"
          repo_token: ${{ secrets.GITHUB_TOKEN }}
