name: Python Linting
on:
  pull_request:
    types:
     - opened
     - reopened
     - edited
     - synchronize
  push:
    branches:
      - master

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Python, pipenv and Pipfile packages
        uses: palewire/install-python-pipenv-pipfile@v3
        with:
          python-version: 3.11

      - name: pip install ruff
        # EnriqueSoria/annotate_pr_with_ruff does not use pipenv install
        run: pip install ruff
        if: github.event_name == 'pull_request'

      - name: PR annotator with ruff
        uses: EnriqueSoria/annotate_pr_with_ruff@v0.1.20
        if: github.event_name == 'pull_request'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Python Black
        uses: cytopia/docker-black@0.11
        if: success() || failure()
        with:
          path: .

      - name: python-isort
        uses: isort/isort-action@v1.1.0
        if: success() || failure()
        with:
          configuration: "--check-only --diff --profile black"
